version: "3"

services:
  apixel-website:
    container_name: apixel-website
    image: node:12
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - /var/apixel-website/.env:/apixel-website/.env
      - /var/apixel-website/public.pem:/apixel-website/public.pem
      - /var/apixel-website/private.key:/apixel-website/private.key